#https://chatgpt.com/c/68da2405-2b00-8328-8336-c8ba66181d61
#Containers (transfer configurations to other machine)
#docker file instucts to install dependencies

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_rootPassword}
      MYSQL_DATABASE: ${MYSQL_database}
      MYSQL_USER: ${MYSQL_user}
      MYSQL_PASSWORD: ${MYSQL_password}
    ports:
      - "3307:3306"
    volumes: #location of the container
      - symfonyTest:/var/lib/mysql
    networks: #if multiple machine
      - symfony_network
    restart: always

  #pasunod og run
  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: FilumentFoundry
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - "8889:80"
    networks:
      - symfony_network
    restart: always


volumes:
  symfonyTest:

networks:
  symfony_network: